# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Use R language
language: r
#Define multiple R-versions, one from bioconductor
r:
  - oldrel
  - release
  - devel
  - bioc-devel
  
cache: packages
